BookingVilla/Controllers/AmenityController.cs
using BookingVilla.Application.Common.Utility;
using BookingVilla.Application.Services.Interface;
using BookingVilla.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BookingVilla.Controllers
{
	[Authorize(Roles = StaticDetails.Roles.Admin)]
    public class AmenityController : Controller
    {
		private readonly IAmenityService _amenityService;
		private readonly IVillaService _villaService;

        public AmenityController(IAmenityService amenityService, IVillaService villaService)
        {
            _amenityService = amenityService;
            _villaService = villaService;
        }

        public IActionResult Index()
        {
            var amenities = _amenityService.GetAllAmenities();
            return View(amenities);
        }

        public IActionResult Create() 
        {
            AmenityVM AmenityVM = new AmenityVM()
            {
                VillaList = _villaService.GetAllVillas().Select(item => new SelectListItem
                {
                    Text = item.Name,
                    Value = item.Id.ToString()
                })
            };
            return View(AmenityVM);
        }

        [HttpPost]
        public IActionResult Create(AmenityVM vN)
        {
            if(ModelState.IsValid)
            {
				_amenityService.CreateAmenity(vN.Amenity);
                TempData["success"] = "Success! The amenity is created successfully.";
                return RedirectToAction(nameof(Index));
            }

            vN.VillaList = _villaService.GetAllVillas().Select(item => new SelectListItem
            {
                Text = item.Name,
                Value = item.Id.ToString()
            });
			return View(vN);
        }

        public IActionResult Update(int amenityId)
        {
			AmenityVM amenityVM = new AmenityVM()
			{
				VillaList = _villaService.GetAllVillas().Select(item => new SelectListItem
				{
					Text = item.Name,
					Value = item.Id.ToString()
				}),
                Amenity = _amenityService.GetAmenityById(amenityId)
			};
			return View(amenityVM);
		}

        [HttpPost]
		public IActionResult Update(AmenityVM AmenityVM)
		{
			if (ModelState.IsValid)
			{
				_amenityService.UpdateAmenity(AmenityVM.Amenity);
				TempData["success"] = "Success! The amenity is updated successfully.";
				return RedirectToAction(nameof(Index));
			}

			AmenityVM.VillaList = _villaService.GetAllVillas().Select(item => new SelectListItem
			{
				Text = item.Name,
				Value = item.Id.ToString()
			});
            return View(AmenityVM);
		}

        public IActionResult Delete(int amenityId) 
        {
			AmenityVM amenityVM = new AmenityVM()
			{
				VillaList = _villaService.GetAllVillas().Select(item => new SelectListItem
				{
					Text = item.Name,
					Value = item.Id.ToString()
				}),
				Amenity = _amenityService.GetAmenityById(amenityId)
			};
			return View(amenityVM);
		}

		[HttpPost]
		public IActionResult Delete(AmenityVM amenityVM)
		{
			if (_amenityService.DeleteAmenity(amenityVM.Amenity.Id))
			{
                TempData["success"] = "Success! The amenity is deleted successfully.";
                return RedirectToAction("Index");
			}
			TempData["error"] = "Error! The amenity could not be deleted";
			return View(nameof(Index));
		}
	}
}

BookingVilla/Controllers/BookingController.cs
using BookingVilla.Application.Common.Utility;
using BookingVilla.Application.Services.Interface;
using BookingVilla.Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Stripe.Checkout;
using Syncfusion.DocIO;
using Syncfusion.DocIO.DLS;
using Syncfusion.DocIORenderer;
using Syncfusion.Drawing;
using Syncfusion.Pdf;
using System.Security.Claims;
using static BookingVilla.Application.Common.Utility.StaticDetails;

namespace BookingVilla.Controllers
{
	public class BookingController : Controller
	{
		private readonly IWebHostEnvironment _webHostEnvironment;
		private readonly IVillaService _villaService;
		private readonly IVillaNumberService _villaNumberService;
		private readonly IBookingService _bookingService;
		private readonly UserManager<AppUser> _userManager;

		public BookingController(IWebHostEnvironment webHostEnvironment,
			IVillaService villaService, IVillaNumberService villaNumberService,
			IBookingService bookingService, UserManager<AppUser> userManager)
		{
			_webHostEnvironment = webHostEnvironment;
			_villaService = villaService;
			_villaNumberService = villaNumberService;
			_bookingService = bookingService;
			_userManager = userManager;
		}

		[Authorize]
		public IActionResult Index()
		{
			return View();
		}

		[Authorize]
		public IActionResult FinalizeBooking(int nights, DateOnly checkInDate, int villaId )
		{
			var claimsIdentity = (ClaimsIdentity)User.Identity;
			var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;
			AppUser user = _userManager.FindByIdAsync(userId).GetAwaiter().GetResult();
			Booking booking = new Booking()
			{
				VillaId = villaId,
				Villa = _villaService.GetVilla(villaId),
				CheckInDate = checkInDate,
				Nights = nights,
				CheckOutDate = checkInDate.AddDays(nights),
				UserId = userId,
				Phone = user.PhoneNumber,
				Email = user.Email,
				Name = user.Name,

			};
			booking.TotalCost = booking.Villa.Price * nights;
			return View(booking);
		}

		[Authorize]
		[HttpPost]
		public IActionResult FinalizeBooking(Booking booking)
		{
			var villa = _villaService.GetVilla(booking.VillaId);
			booking.TotalCost = villa.Price * booking.Nights;
			booking.Status = BookStatus.StatusPending;
			booking.BookingDate = DateTime.Now;

			if (!_villaService.IsAvailableVillaByDate(villa.Id, booking.Nights, booking.CheckInDate))
			{
				TempData["error"] = "Room has been sold out";
				return RedirectToAction(nameof(FinalizeBooking), new
				{
					villaId = villa.Id,
					checkInDate = booking.CheckInDate,
					nights = booking.Nights
				});
			}
            _bookingService.CreateBooking(booking);

			var domain = $"{Request.Scheme}://{Request.Host.Value}/";
			var options = new SessionCreateOptions
			{
				LineItems = new List<SessionLineItemOptions>(),
				Mode = "payment",
				SuccessUrl = domain + $"Booking/BookingConfirmation?bookingId={booking.Id}",
				CancelUrl = domain + $"Booking/FinalizeBooking?villaId={booking.VillaId}&checkInDate={booking.CheckInDate}&nights{booking.Nights}",
			};

			options.LineItems.Add(new SessionLineItemOptions
			{
				PriceData = new SessionLineItemPriceDataOptions()
				{
					UnitAmount = (long)(booking.TotalCost * 100),
					Currency = "usd",
					ProductData = new SessionLineItemPriceDataProductDataOptions()
					{
						Name = villa.Name,
					}
				},
				Quantity = 1
			});
			var service = new SessionService();
			Session session = service.Create(options);
			_bookingService.UpdateStripePaymentId(booking.Id, session.Id, session.PaymentIntentId);
			Response.Headers.Add("Location", session.Url);
			return new StatusCodeResult(303);
		}

		[Authorize]
		public IActionResult BookingConfirmation(int bookingId)
		{
			Booking booking = _bookingService.GetBookingById(bookingId);

			if (booking.Status == BookStatus.StatusPending )
			{
				var service = new SessionService();
				Session session = service.Get(booking.StripeSessionId);

				if (session.PaymentStatus == "paid")
				{
					_bookingService.UpdateStatus(booking.Id, BookStatus.StatusApproved, 0);
                    _bookingService.UpdateStripePaymentId(booking.Id,session.Id, session.PaymentIntentId);
				}
			}
			return View(bookingId);
		}

		[Authorize]
		public IActionResult BookingDetails(int bookingId)
		{
			Booking booking = _bookingService.GetBookingById(bookingId);

			if (booking.VillaNumber == 0 && booking.Status == BookStatus.StatusApproved)
			{
				var availableVillaNumber = AssignAvailableVillaNumberByVilla(booking.VillaId);
				booking.VillaNumbers = _villaNumberService.GetAllVillaNumbers().Where(u => u.VillaId == booking.VillaId
				&& availableVillaNumber.Any(x => x == u.Villa_Number)).ToList();
			}
			return View(booking);
		}

		[HttpPost]
		[Authorize]
		public IActionResult GenerateInvoice(int id, string downloadType)
		{
			string basePath = _webHostEnvironment.WebRootPath;
			WordDocument document = new();
			//Load Template
			string dataPath = $"{basePath}/exports/BookingDetails.docx";
			using FileStream fileStream = new(
				dataPath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
			document.Open(fileStream, FormatType.Automatic);

			//Update Template
			Booking booking = _bookingService.GetBookingById(id);
			TextSelection textSelection = document.Find(
				"xx_customer_name", false, true);
			WTextRange textRange = textSelection.GetAsOneRange();
			textRange.Text = booking.User.Name;

			textSelection = document.Find("xx_customer_email", false, true);
			textRange = textSelection.GetAsOneRange();
			textRange.Text = booking.Email;

            textSelection = document.Find("xx_customer_phone", false, true);
            textRange = textSelection.GetAsOneRange();
            textRange.Text = booking.User.PhoneNumber;

            textSelection = document.Find("xx_BOOKING_NUMBER", false, true);
            textRange = textSelection.GetAsOneRange();
            textRange.Text = $"Booking Id - {booking.Id}";

            textSelection = document.Find("xx_BOOKING_DATE", false, true);
            textRange = textSelection.GetAsOneRange();
            textRange.Text = $"Booking Date - {booking.BookingDate.ToShortDateString()}";

            textSelection = document.Find("xx_payment_date", false, true);
            textRange = textSelection.GetAsOneRange();
            textRange.Text = booking.PaymentDate.ToShortDateString();

            textSelection = document.Find("xx_checkin_date", false, true);
            textRange = textSelection.GetAsOneRange();
            textRange.Text = booking.CheckInDate.ToShortDateString();

            textSelection = document.Find("xx_checkout_date", false, true);
            textRange = textSelection.GetAsOneRange();
            textRange.Text = booking.CheckOutDate.ToShortDateString();

            textSelection = document.Find("xx_booking_total", false, true);
            textRange = textSelection.GetAsOneRange();
            textRange.Text = booking.TotalCost.ToString("c");

			WTable table = new (document);
			table.TableFormat.Borders.LineWidth = 1f;
			table.TableFormat.Borders.Color = Color.Black;
			table.TableFormat.Paddings.Top = 7f;
			table.TableFormat.Paddings.Bottom = 7f;
			table.TableFormat.Borders.Horizontal.LineWidth = 1f;

			int rows = booking.VillaNumber > 0 ? 3 : 2;
			table.ResetCells(rows, 4);

			WTableRow row0 = table.Rows[0];
			row0.Cells[0].AddParagraph().AppendText("Nights");
			row0.Cells[0].Width = 80;
			row0.Cells[1].AddParagraph().AppendText("Villa");
			row0.Cells[1].Width = 220;
			row0.Cells[2].AddParagraph().AppendText("Price Per Night");
			row0.Cells[3].AddParagraph().AppendText("Total");
			row0.Cells[3].Width = 80;

			WTableRow row1 = table.Rows[1];
			row1.Cells[0].AddParagraph().AppendText(booking.Nights.ToString());
			row1.Cells[0].Width = 80;
			row1.Cells[1].AddParagraph().AppendText(booking.Villa.Name);
            row1.Cells[1].Width = 220;
            row1.Cells[2].AddParagraph().AppendText((booking.TotalCost / booking.Nights).ToString());
			row1.Cells[3].AddParagraph().AppendText((booking.TotalCost).ToString("c"));
            row1.Cells[3].Width = 80;

			if (booking.VillaNumber > 0)
			{
                WTableRow row2 = table.Rows[2];
                row2.Cells[0].Width = 80;
                row2.Cells[1].AddParagraph().AppendText($"Villa Number - {booking.VillaNumber}");
                row2.Cells[1].Width = 220;
                row2.Cells[3].Width = 80;
            }

			WTableStyle tableStyle = document.AddTableStyle("CustomStyle") as WTableStyle;
			tableStyle.TableProperties.RowStripe = 1;
			tableStyle.TableProperties.ColumnStripe = 2;
			tableStyle.TableProperties.Paddings.Top = 2;
			tableStyle.TableProperties.Paddings.Bottom = 1;
			tableStyle.TableProperties.Paddings.Left = 5.4f;
			tableStyle.TableProperties.Paddings.Right = 5.4f;

			ConditionalFormattingStyle firstRowStyle = tableStyle.
				ConditionalFormattingStyles.Add(ConditionalFormattingType.FirstRow);
			firstRowStyle.CharacterFormat.Bold = true;
			firstRowStyle.CharacterFormat.TextColor = Color.FromArgb(255, 255, 255, 255);
			firstRowStyle.CellProperties.BackColor = Color.Black;

			table.ApplyStyle("CustomStyle");

			TextBodyPart textBodyPart = new (document);
			textBodyPart.BodyItems.Add(table);

			document.Replace("<ADDTABLEHERE>", textBodyPart, false, false);

            using DocIORenderer renderer = new ();
			MemoryStream stream = new ();

			if (downloadType == "word")
			{
                document.Save(stream, FormatType.Docx);
                stream.Position = 0;

                return File(stream, "application/docx", "BookingDetails.docx");
            }
			else
			{
				PdfDocument pdfDocument= renderer.ConvertToPDF(document);
				pdfDocument.Save(stream);
				stream.Position = 0;

				return File(stream, "application/pdf", "BookingDetails.pdf");
			}
		}

        [HttpPost]
		[Authorize(Roles = Roles.Admin)]

BookingVilla/Controllers/DashboardController.cs
using BookingVilla.Application.Services.Interface;
using Microsoft.AspNetCore.Mvc;

namespace BookingVilla.Controllers
{
    public class DashboardController : Controller
    {
        private readonly IDashboardService _dashboardService;

        public DashboardController(IDashboardService dashboardService)
        {
            _dashboardService = dashboardService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetTotalBookingsRadialChartData()
        {
            return Json(await _dashboardService.GetTotalBookingsRadialChartData());
        }

        public async Task<IActionResult> GetRegisteredUsersRadialChartData()
        {
            return Json( await _dashboardService.GetRegisteredUsersRadialChartData());
        }

        public async Task<IActionResult> GetTotalRevenueRadialChartData()
        {
            return Json(await _dashboardService.GetTotalRevenueRadialChartData());
        }

		public async Task<IActionResult> GetBookingsPieChartData()
		{
			return Json(await _dashboardService.GetBookingsPieChartData());
		}

        public async Task<IActionResult> GetMemberAndBookingLineChartData()
        {
            return Json(await _dashboardService.GetMemberAndBookingLineChartData());
        }
    }
}

BookingVilla/Controllers/VillaController.cs
using BookingVilla.Application.Services.Interface;
using BookingVilla.Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BookingVilla.Controllers
{
	[Authorize]
	public class VillaController : Controller
	{
		private readonly IVillaService _villaService;

        public VillaController(IVillaService villaService)
        {
			_villaService = villaService;
        }

        public IActionResult Index()
		{
			var villas = _villaService.GetAllVillas();
			return View(villas);
		}

		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Create(Villa villa)
		{
			if (villa.Name == villa.Description)
			{
				ModelState.AddModelError("", "The name and description should be differ");
			}
			if (ModelState.IsValid)
			{
				_villaService.CreateVilla(villa);
				TempData["success"] = "Success! The villa is created successfully.";
				return RedirectToAction(nameof(Index));
			}
			return View();
		}

		public IActionResult Update(int villaId)
		{
			Villa? villa = _villaService.GetVilla(villaId);
			if (villa == null)
			{
				return RedirectToAction("Error", "Home");
			}
			return View(villa);
		}

		[HttpPost]
		public IActionResult Update(Villa villa)
		{
			if (ModelState.IsValid && villa.Id > 0)
			{
				_villaService.UpdateVilla(villa);
				TempData["success"] = "Success! The villa is updated successfully.";
				return RedirectToAction(nameof(Index));
			}
			return View(nameof(Index));
		}


		public IActionResult Delete(int villaId)
		{
			Villa? villa = _villaService.GetVilla(villaId);
			if (villa == null)
			{
				return RedirectToAction("Error", "Home");
			}
			return View(villa);
		}

		[HttpPost]
		public IActionResult Delete(Villa villa)
		{
			bool deleted = _villaService.DeleteVilla(villa.Id);

			if (deleted) 
			{
                TempData["success"] = "Success! The villa is deleted successfully.";
                return RedirectToAction(nameof(Index));
            }
			else
			{
                TempData["error"] = "Failed to delete villa.";
            }
			return View();
		}
	}
}

BookingVilla/Views/Shared/_Layout.cshtml
@using BookingVilla.Application.Common.Utility

<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookingVilla</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/css/bootstrap.min.css" integrity="sha512-b2QcS5SsA8tZodcDtGRELiGv5SaKSk1vDHDaQRda0htPYWZ6046lr3kJ5bAAQdpV2mmA/4v0wQF9MyU6/pDIAg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="~/BookingVilla.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/spinner.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/Images/resort.png" width="35"></img></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole(Roles.Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Management
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Villa" asp-action="Index">Villas</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="VillaNumber" asp-action="Index">Villa Numbers</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Amenity" asp-action="Index">Amenities</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Booking" asp-action="Index" asp-route-status="@StaticDetails.BookStatus.StatusApproved">Bookings</a></li>
                                </ul>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link " asp-controller="Booking" asp-action="Index"> Manage Bookings</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartialView" />
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main">
            <div class="loading spinner" style="display:none"></div>
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy;Made with love</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/js/bootstrap.bundle.min.js" integrity="sha512-X/YkDZyjTf4wyc2Vy16YGCPHwAY8rZJY+POgokZjQB2mhIRFJCckEGc6YyX9eNsPfn0PzThEuNs+uaomE5CO6A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js"asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BookingVilla/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - BookingVilla</title>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/css/bootstrap.min.css" integrity="sha512-b2QcS5SsA8tZodcDtGRELiGv5SaKSk1vDHDaQRda0htPYWZ6046lr3kJ5bAAQdpV2mmA/4v0wQF9MyU6/pDIAg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
	<link rel="stylesheet" href="~/BookingVilla.styles.css" asp-append-version="true" />
	<link rel="stylesheet" href="~/css/spinner.css" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link rel="stylesheet" href="//cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css" />
	<link rel="stylesheet" href="~/css/apexcharts.css"></link>
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow">
			<div class="container-fluid d-flex justify-content-between">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/Images/resort.png" width="35"></img></a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
			</div>
			<partial name="_LoginPartialViewAdmin" />
		</nav>
	</header>
	<div class="container-fluid">
		<div class="loading spinner" style="display:none"></div>
		<div class="row">
			<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-dark sidebar collapse">
				<div class="position-static pt-3">
					<ul class="navbar-nav">
						<li>
							<div class="text-muted small fw-bold text-uppercase px-3">
								Menu
							</div>
						</li>
						<li class="nav-item">
							<a class="nav-link " asp-controller="Dashboard" asp-action="Index">
								<span class="me-2"><i class="bi bi-speedometer2"></i></span>
								<span>Dashboard</span>
							</a>
						</li>
						<li>
							<div class="text-muted small fw-bold text-uppercase px-3">
								Content Management
							</div>
						</li>
						<li class="nav-item">
							<a class="nav-link " asp-controller="Villa" asp-action="Index">
								<span class="me-2"><i class="bi bi-speedometer2"></i></span>
								<span>Villa</span>
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link " asp-controller="VillaNumber" asp-action="Index">
								<span class="me-2"><i class="bi bi-speedometer2"></i></span>
								<span>Villa Number</span>
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link " asp-controller="Amenity" asp-action="Index">
								<span class="me-2"><i class="bi bi-speedometer2"></i></span>
								<span>Amenity</span>
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link " asp-controller="Booking" asp-action="Index" asp-route-status="Approved">
								<span class="me-2"><i class="bi bi-speedometer2"></i></span>
								<span>Bookings</span>
							</a>
						</li>
					</ul>
				</div>
			</nav>
			<main class="col-md-9 me-sm-auto col-lg-10 px-md-4">
				<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 w-100">
					<partial name="_Notification" />
					@RenderBody()
				</div>
			</main>
		</div>
	</div>

	<footer class="border-top footer text-muted">
		<div class="container">
			&copy;Made with love</a>
		</div>
	</footer>
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/js/bootstrap.bundle.min.js" integrity="sha512-X/YkDZyjTf4wyc2Vy16YGCPHwAY8rZJY+POgokZjQB2mhIRFJCckEGc6YyX9eNsPfn0PzThEuNs+uaomE5CO6A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="//cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js" asp-append-version="true"></script>
	<script src="~/js/apexcharts.js"></script>
	<script src="~/js/dashboard/radialChart.js"></script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>