BookingVilla/Controllers/VillaController.cs
using BookingVilla.Application.Services.Interface;
using BookingVilla.Domain.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BookingVilla.Controllers
{
	[Authorize]
	public class VillaController : Controller
	{
		private readonly IVillaService _villaService;

        public VillaController(IVillaService villaService)
        {
			_villaService = villaService;
        }

        public IActionResult Index()
		{
			var villas = _villaService.GetAllVillas();
			return View(villas);
		}

		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Create(Villa villa)
		{
			if (villa.Name == villa.Description)
			{
				ModelState.AddModelError("", "The name and description should be differ");
			}
			if (ModelState.IsValid)
			{
				_villaService.CreateVilla(villa);
				TempData["success"] = "Success! The villa is created successfully.";
				return RedirectToAction(nameof(Index));
			}
			return View();
		}

		public IActionResult Update(int villaId)
		{
			Villa? villa = _villaService.GetVilla(villaId);
			if (villa == null)
			{
				return RedirectToAction("Error", "Home");
			}
			return View(villa);
		}

		[HttpPost]
		public IActionResult Update(Villa villa)
		{
			if (ModelState.IsValid && villa.Id > 0)
			{
				_villaService.UpdateVilla(villa);
				TempData["success"] = "Success! The villa is updated successfully.";
				return RedirectToAction(nameof(Index));
			}
			return View(nameof(Index));
		}


		public IActionResult Delete(int villaId)
		{
			Villa? villa = _villaService.GetVilla(villaId);
			if (villa == null)
			{
				return RedirectToAction("Error", "Home");
			}
			return View(villa);
		}

		[HttpPost]
		public IActionResult Delete(Villa villa)
		{
			bool deleted = _villaService.DeleteVilla(villa.Id);

			if (deleted) 
			{
                TempData["success"] = "Success! The villa is deleted successfully.";
                return RedirectToAction(nameof(Index));
            }
			else
			{
                TempData["error"] = "Failed to delete villa.";
            }
			return View();
		}
	}
}

BookingVilla/Views/Villa/Create.cshtml
@model BookingVilla.Domain.Entities.Villa

<div class="w-100 card border-0 p-4">
	<div class="card-header bg-dark bg-gradient m-lg-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h1 class="text-white-50 py-2">Create Villa</h1>
			</div>
		</div>
	</div>
	<div class="card-body border p-4">
		<form method="post" class="row" enctype="multipart/form-data">
			<div class="p-3">
				<div asp-validation-summary="ModelOnly" class="text-info"></div>
				<div class="form-floating py-1 col-12">
					<input asp-for="Name" class="form-control border shadow" />
					<label asp-for="Name" class="ms-2"></label>
					<span asp-validation-for="Name" class="text-danger"></span>
				</div>
				<div class="form-floating py-1 col-12">
					<input asp-for="Description" class="form-control border shadow" />
					<label asp-for="Description" class="ms-2"></label>
					<span asp-validation-for="Description" class="text-danger"></span>
				</div>
				<div class="form-floating py-1 col-12">
					<input asp-for="Price" class="form-control border shadow" />
					<label asp-for="Price" class="ms-2"></label>
					<span asp-validation-for="Price" class="text-danger"></span>
				</div>
				<div class="form-floating py-1 col-12">
					<input asp-for="Sqft" class="form-control border shadow" />
					<label asp-for="Sqft" class="ms-2"></label>
					<span asp-validation-for="Sqft" class="text-danger"></span>
				</div>
				<div class="form-floating py-1 col-12">
					<input asp-for="Occupancy" class="form-control border shadow" />
					<label asp-for="Occupancy" class="ms-2"></label>
					<span asp-validation-for="Occupancy" class="text-danger"></span>
				</div>
				<div class="form-floating py-1 col-12">
					<input asp-for="ImageUrl" hidden class="form-control border shadow" />
					<input asp-for="Image" class="form-control border shadow" />
					<label asp-for="ImageUrl" class="ms-2"></label>
				</div>
			</div>
			<div class="row pt-2">
				<div class="col-6 col-md-5">
					<button type="submit" class="btn btn-success w-100 justify-content-center d-flex">
						<i class="bi bi-plus-circle-dotted"></i> Create
					</button>
				</div>
				<div class="col-6 col-md-5">
					<a asp-controller="Villa" asp-action="Index" class="btn btn-secondary w-100 justify-content-center d-flex">
						<i class="bi bi-x-circle"></i> Cancel
					</a>
				</div>
			</div>
		</form>
	</div>
</div>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial"/>
	}
}

BookingVilla/Views/Villa/Delete.cshtml
@model BookingVilla.Domain.Entities.Villa

<div class="w-100 card border-0 p-4">
	<div class="card-header bg-dark bg-gradient m-lg-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h1 class="text-white-50 py-2">Delete Villa</h1>
			</div>
		</div>
	</div>
	<div class="card-body border p-4">
		<form method="post" class="row">
			<input asp-for="Id" hidden />
			<div class="col-10">
				<div class="p-3">
					<div class="form-floating py-1 col-12">
						<input asp-for="Name" disabled class="form-control border shadow" />
						<label asp-for="Name" class="ms-2"></label>
					</div>
					<div class="form-floating py-1 col-12">
						<input asp-for="Description" disabled class="form-control border shadow" />
						<label asp-for="Description" class="ms-2"></label>
					</div>
					<div class="form-floating py-1 col-12">
						<input asp-for="Price" disabled class="form-control border shadow" />
						<label asp-for="Price" class="ms-2"></label>
					</div>
					<div class="form-floating py-1 col-12">
						<input asp-for="Sqft" disabled class="form-control border shadow" />
						<label asp-for="Sqft" class="ms-2"></label>
					</div>
					<div class="form-floating py-1 col-12">
						<input asp-for="Occupancy" disabled class="form-control border shadow" />
						<label asp-for="Occupancy" class="ms-2"></label>
					</div>
					<div class="form-floating py-1 col-12">
						<input asp-for="ImageUrl"  disabled class="form-control border shadow" />
						<label asp-for="ImageUrl" class="ms-2"></label>
					</div>
				</div>
			</div>
			<div class="col-2">
				<img src="@Model.ImageUrl" width="100%"
					 style="border-radius:5px; border:1px solid #bbb9b9" />
			</div>
			<div class="row pt-2">
				<div class="col-6 col-md-5">
					<button type="submit" class="btn btn-danger w-100 justify-content-center d-flex">
						<i class="bi bi-pen-fill"></i> Delete
					</button>
				</div>
				<div class="col-6 col-md-5">
					<a asp-controller="Villa" asp-action="Index" class="btn btn-secondary w-100 justify-content-center d-flex">
						<i class="bi bi-x-circle"></i> Cancel
					</a>
				</div>
			</div>
		</form>
	</div>
</div>

BookingVilla/Views/Villa/Index.cshtml
@model IEnumerable<BookingVilla.Domain.Entities.Villa>

<div class="w-100 card border-0 p-4">
	<div class="card-header bg-dark bg-gradient m-lg-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h1 class="text-white-50 py-2">Villas</h1>
			</div>
		</div>
		<div class="card-body border p-4">
			<table class="table table-bordered table-striped">
				<thead>
					<tr>
						<th class="card-header bg-light text-black">Name</th>
						<th class="card-header bg-light text-black">Price</th>
						<th class="card-header bg-light text-black">Square Feet</th>
						<th class="card-header bg-light text-black">Occupancy</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					@foreach (var villa in Model)
					{
						<tr>
							<td class="card-body bg-light text-black"> <i class="bi bi-house"></i> @villa.Name</td>
							<td class="card-body bg-light text-black"> <i class="bi bi-cash"></i> @villa.Price</td>
							<td class="card-body bg-light text-black"> <i class="bi bi-2-square"></i> @villa.Sqft</td>
							<td class="card-body bg-light text-black"> <i class="bi bi-people-fill"></i> @villa.Occupancy</td>
							<td>
								<div class="w-75 btn-group" role="group">
									<a asp-controller="Villa" asp-action="Update" class="btn btn-success" asp-route-villaId="@villa.Id"> <i class="bi bi-pen-fill"></i>Update</a>
									<a asp-controller="Villa" asp-action="Delete" class="btn btn-danger" asp-route-villaId="@villa.Id"><i class="bi bi-trash-fill"></i> Delete</a>
								</div>
								
							</td>
						</tr>
					}
				</tbody>
			</table>
			<div class="row pb-3">
				<div class="col-6 offset-6 text-end">
					<a asp-controller="Villa" asp-action="Create" class="btn btn-success">
						<i class="bi bi-plus-circle-dotted"></i> Create New Villa
					</a>
				</div>
			</div>
		</div>
	</div>
</div>

BookingVilla/Views/Villa/Update.cshtml
@model BookingVilla.Domain.Entities.Villa

<div class="w-100 card border-0 p-4">
	<div class="card-header bg-dark bg-gradient m-lg-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h1 class="text-white-50 py-2">Update Villa</h1>
			</div>
		</div>
	</div>
	<div class="card-body border p-4">
		<form method="post" class="row" enctype="multipart/form-data">
			<input asp-for="Id" hidden/>
			<div class="col-10">
				<div class="p-3">
					<div asp-validation-summary="ModelOnly" class="text-info"></div>
					<div class="form-floating py-1 col-12">
						<input asp-for="Name" class="form-control border shadow" />
						<label asp-for="Name" class="ms-2"></label>
						<span asp-validation-for="Name" class="text-danger"></span>
					</div>
					<div class="form-floating py-1 col-12">
						<input asp-for="Description" class="form-control border shadow" />
						<label asp-for="Description" class="ms-2"></label>
						<span asp-validation-for="Description" class="text-danger"></span>
					</div>
					<div class="form-floating py-1 col-12">
						<input asp-for="Price" class="form-control border shadow" />
						<label asp-for="Price" class="ms-2"></label>
						<span asp-validation-for="Price" class="text-danger"></span>
					</div>
					<div class="form-floating py-1 col-12">
						<input asp-for="Sqft" class="form-control border shadow" />
						<label asp-for="Sqft" class="ms-2"></label>
						<span asp-validation-for="Sqft" class="text-danger"></span>
					</div>
					<div class="form-floating py-1 col-12">
						<input asp-for="Occupancy" class="form-control border shadow" />
						<label asp-for="Occupancy" class="ms-2"></label>
						<span asp-validation-for="Occupancy" class="text-danger"></span>
					</div>
					<div class="form-floating py-1 col-12">
						<input asp-for="Image" class="form-control border shadow" />
						<input asp-for="ImageUrl" hidden class="form-control border shadow" />
						<label asp-for="ImageUrl" class="ms-2"></label>
					</div>
				</div>
			</div>
			<div class="col-2">
				<img src="@Model.ImageUrl" width="100%"
				style="border-radius:5px; border:1px solid #bbb9b9"/>
			</div>
			<div class="row pt-2">
				<div class="col-6 col-md-5">
					<button type="submit" class="btn btn-success w-100 justify-content-center d-flex">
						<i class="bi bi-pen-fill"></i> Update
					</button>
				</div>
				<div class="col-6 col-md-5">
					<a asp-controller="Villa" asp-action="Index" class="btn btn-secondary w-100 justify-content-center d-flex">
						<i class="bi bi-x-circle"></i> Cancel
					</a>
				</div>
			</div>
		</form>
	</div>
</div>

@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}