BookingVilla/Controllers/AmenityController.cs
using BookingVilla.Application.Common.Utility;
using BookingVilla.Application.Services.Interface;
using BookingVilla.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BookingVilla.Controllers
{
	[Authorize(Roles = StaticDetails.Roles.Admin)]
    public class AmenityController : Controller
    {
		private readonly IAmenityService _amenityService;
		private readonly IVillaService _villaService;

        public AmenityController(IAmenityService amenityService, IVillaService villaService)
        {
            _amenityService = amenityService;
            _villaService = villaService;
        }

        public IActionResult Index()
        {
            var amenities = _amenityService.GetAllAmenities();
            return View(amenities);
        }

        public IActionResult Create() 
        {
            AmenityVM AmenityVM = new AmenityVM()
            {
                VillaList = _villaService.GetAllVillas().Select(item => new SelectListItem
                {
                    Text = item.Name,
                    Value = item.Id.ToString()
                })
            };
            return View(AmenityVM);
        }

        [HttpPost]
        public IActionResult Create(AmenityVM vN)
        {
            if(ModelState.IsValid)
            {
				_amenityService.CreateAmenity(vN.Amenity);
                TempData["success"] = "Success! The amenity is created successfully.";
                return RedirectToAction(nameof(Index));
            }

            vN.VillaList = _villaService.GetAllVillas().Select(item => new SelectListItem
            {
                Text = item.Name,
                Value = item.Id.ToString()
            });
			return View(vN);
        }

        public IActionResult Update(int amenityId)
        {
			AmenityVM amenityVM = new AmenityVM()
			{
				VillaList = _villaService.GetAllVillas().Select(item => new SelectListItem
				{
					Text = item.Name,
					Value = item.Id.ToString()
				}),
                Amenity = _amenityService.GetAmenityById(amenityId)
			};
			return View(amenityVM);
		}

        [HttpPost]
		public IActionResult Update(AmenityVM AmenityVM)
		{
			if (ModelState.IsValid)
			{
				_amenityService.UpdateAmenity(AmenityVM.Amenity);
				TempData["success"] = "Success! The amenity is updated successfully.";
				return RedirectToAction(nameof(Index));
			}

			AmenityVM.VillaList = _villaService.GetAllVillas().Select(item => new SelectListItem
			{
				Text = item.Name,
				Value = item.Id.ToString()
			});
            return View(AmenityVM);
		}

        public IActionResult Delete(int amenityId) 
        {
			AmenityVM amenityVM = new AmenityVM()
			{
				VillaList = _villaService.GetAllVillas().Select(item => new SelectListItem
				{
					Text = item.Name,
					Value = item.Id.ToString()
				}),
				Amenity = _amenityService.GetAmenityById(amenityId)
			};
			return View(amenityVM);
		}

		[HttpPost]
		public IActionResult Delete(AmenityVM amenityVM)
		{
			if (_amenityService.DeleteAmenity(amenityVM.Amenity.Id))
			{
                TempData["success"] = "Success! The amenity is deleted successfully.";
                return RedirectToAction("Index");
			}
			TempData["error"] = "Error! The amenity could not be deleted";
			return View(nameof(Index));
		}
	}
}

BookingVilla/Controllers/VillaNumberController.cs
using BookingVilla.Application.Services.Interface;
using BookingVilla.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BookingVilla.Controllers
{
    public class VillaNumberController : Controller
    {
		private readonly IVillaNumberService _villaNumberService;
        private readonly IVillaService _villaService;

        public VillaNumberController(IVillaNumberService villaNumberService, IVillaService villaService)
        {
            _villaNumberService = villaNumberService;
            _villaService = villaService;
        }

        public IActionResult Index()
        {
            var villaNumbers = _villaNumberService.GetAllVillaNumbers();
            return View(villaNumbers);
        }

        public IActionResult Create() 
        {
            VillaNumberVM villaNumberVM = new VillaNumberVM()
            {
                VillaList = _villaService.GetAllVillas().Select(item => new SelectListItem
                {
                    Text = item.Name,
                    Value = item.Id.ToString()
                })
            };
            return View(villaNumberVM);
        }

        [HttpPost]
        public IActionResult Create(VillaNumberVM vN)
        {
            if(ModelState.IsValid)
            {
                _villaNumberService.CreateVillaNumber(vN.VillaNumber);
                TempData["success"] = "Success! The villa number is created successfully.";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                TempData["error"] = "The villa number already exists!";
            }

            vN.VillaList = _villaService.GetAllVillas().Select(item => new SelectListItem
            {
                Text = item.Name,
                Value = item.Id.ToString()
            });
			return View(vN);
        }

        public IActionResult Update(int villaNumberId)
        {
			VillaNumberVM villaNumberVM = new VillaNumberVM()
			{
				VillaList = _villaService.GetAllVillas().Select(item => new SelectListItem
				{
					Text = item.Name,
					Value = item.Id.ToString()
				}),
                VillaNumber = _villaNumberService.GetVillaNumber(villaNumberId)
			};
			return View(villaNumberVM);
		}

        [HttpPost]
		public IActionResult Update(VillaNumberVM villaNumberVm)
		{
			if (ModelState.IsValid)
			{
				_villaNumberService.UpdateVillaNumber(villaNumberVm.VillaNumber);
				TempData["success"] = "Success! The villa number is updated successfully.";
				return RedirectToAction(nameof(Index));
			}

			villaNumberVm.VillaList = _villaService.GetAllVillas().Select(item => new SelectListItem
			{
				Text = item.Name,
				Value = item.Id.ToString()
			});
            return View(villaNumberVm);
		}

        public IActionResult Delete(int villaNumberId) 
        {
			VillaNumberVM villaNumberVM = new VillaNumberVM()
			{
				VillaList = _villaService.GetAllVillas().Select(item => new SelectListItem
				{
					Text = item.Name,
					Value = item.Id.ToString()
				}),
				VillaNumber = _villaNumberService.GetVillaNumber(villaNumberId)
			};
			return View(villaNumberVM);
		}

		[HttpPost]
		public IActionResult Delete(VillaNumberVM villaNumberVm)
		{
			if (_villaNumberService.DeleteVillaNumber(villaNumberVm.VillaNumber.Villa_Number))
			{
                TempData["success"] = "Success! The villa number is deleted successfully.";
                return RedirectToAction("Index");
			}
			TempData["error"] = "Error! The villa number could not be deleted";
			return View(nameof(Index));
		}
	}
}

BookingVilla/Views/Amenity/Create.cshtml
@model BookingVilla.ViewModels.AmenityVM

<div class="w-100 card border-0 p-4">
	<div class="card-header bg-dark bg-gradient m-lg-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h1 class="text-white-50 py-2">Create Amenity</h1>
			</div>
		</div>
	</div>
	<div class="card-body border p-4">
		<form method="post" class="row">
			<div class="p-3">
				<div asp-validation-summary="ModelOnly" class="text-info"></div>
				<div class="form-floating py-1 col-12">
					<select asp-for="@Model.Amenity.VillaId" asp-items="@Model.VillaList"
							class="form-select border shadow">
						<option disabled selected>- Select Villa - </option>
					</select>
					<label asp-for="Amenity.VillaId" class="ms-2"></label>
					<span asp-validation-for="Amenity.VillaId" class="text-danger"></span>
				</div>
				<div class="form-floating py-1 col-12">
					<input asp-for="Amenity.Name" class="form-control border shadow" />
					<label asp-for="Amenity.Name" class="ms-2"></label>
					<span asp-validation-for="Amenity.Id" class="text-danger"></span>
				</div>
				<div class="form-floating py-1 col-12">
					<input asp-for="Amenity.Description" class="form-control border shadow" />
					<label asp-for="Amenity.Description" class="ms-2"></label>
					<span asp-validation-for="Amenity.Description" class="text-danger"></span>
				</div>
			</div>
			<div class="row pt-2">
				<div class="col-6 col-md-5">
					<button type="submit" class="btn btn-success w-100 justify-content-center d-flex">
						<i class="bi bi-plus-circle-dotted"></i> Create
					</button>
				</div>
				<div class="col-6 col-md-5">
					<a asp-controller="Amenity" asp-action="Index" class="btn btn-secondary w-100 justify-content-center d-flex">
						<i class="bi bi-x-circle"></i> Cancel
					</a>
				</div>
			</div>
		</form>
	</div>
</div>

@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

BookingVilla/Views/Amenity/Delete.cshtml
@model BookingVilla.ViewModels.AmenityVM

<div class="w-100 card border-0 p-4">
	<div class="card-header bg-dark bg-gradient m-lg-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h1 class="text-white-50 py-2">Delete Amenity</h1>
			</div>
		</div>
	</div>
	<div class="card-body border p-4">
		<form method="post" class="row">
			<input asp-for="Amenity.Id" hidden />
			<div class="p-3">
				<div asp-validation-summary="ModelOnly" class="text-info"></div>
				<div class="form-floating py-1 col-12">
					<select asp-for="@Model.Amenity.VillaId" asp-items="@Model.VillaList"
							class="form-select border shadow" disabled>
						<option disabled selected>- Select Villa - </option>
					</select>
					<label asp-for="Amenity.VillaId" class="ms-2"></label>
					<span asp-validation-for="Amenity.VillaId" class="text-danger"></span>
				</div>
				<div class="form-floating py-1 col-12">
					<input asp-for="Amenity.Name" disabled class="form-control border shadow" />
					<label asp-for="Amenity.Name" class="ms-2"></label>
					<span asp-validation-for="Amenity.Name" class="text-danger"></span>
				</div>
				<div class="form-floating py-1 col-12">
					<input asp-for="Amenity.Description" disabled class="form-control border shadow" />
					<label asp-for="Amenity.Description" class="ms-2"></label>
					<span asp-validation-for="Amenity.Description" class="text-danger"></span>
				</div>
			</div>
			<div class="row pt-2">
				<div class="col-6 col-md-5">
					<button type="submit" class="btn btn-danger w-100 justify-content-center d-flex">
						<i class="bi bi-plus-circle-dotted"></i> Delete
					</button>
				</div>
				<div class="col-6 col-md-5">
					<a asp-controller="VillaNumber" asp-action="Index" class="btn btn-secondary w-100 justify-content-center d-flex">
						<i class="bi bi-x-circle"></i> Cancel
					</a>
				</div>
			</div>
		</form>
	</div>
</div>

@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}

BookingVilla/Views/Amenity/Index.cshtml
@model IEnumerable<BookingVilla.Domain.Entities.Amenity>

<div class="w-100 card border-0 p-4">
	<div class="card-header bg-dark bg-gradient m-lg-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h1 class="text-white-50 py-2">Amenities</h1>
			</div>
		</div>
		<div class="card-body border p-4">
			<table class="table table-bordered table-striped">
				<thead>
					<tr>
						<th class="card-header bg-light text-black">Amenity Id</th>
						<th class="card-header bg-light text-black">Name</th>
						<th class="card-header bg-light text-black">Villa Name</th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					@foreach (var amenity in Model)
					{
						<tr>
							<td class="card-body bg-light text-black"> <i class="bi bi-house-check"></i> @amenity.Id</td>
							<td class="card-body bg-light text-black"> <i class="bi bi-key"></i> @amenity.Name</td>
							<td class="card-body bg-light text-black"> <i class="bi bi-journal-text"></i> @amenity.Villa.Name</td>
							<td>
								<div class="w-75 btn-group" role="group">
									<a asp-controller="Amenity" asp-action="Update" class="btn btn-success" asp-route-amenityId="@amenity.Id"> <i class="bi bi-pen-fill"></i>Update</a>
									<a asp-controller="Amenity" asp-action="Delete" class="btn btn-danger" asp-route-amenityId="@amenity.Id"><i class="bi bi-trash-fill"></i> Delete</a>
								</div>

							</td>
						</tr>
					}
				</tbody>
			</table>
			<div class="row pb-3">
				<div class="col-6 offset-6 text-end">
					<a asp-controller="Amenity" asp-action="Create" class="btn btn-success">
						<i class="bi bi-plus-circle-dotted"></i> Create New Amenity
					</a>
				</div>
			</div>
		</div>
	</div>
</div>

BookingVilla/Views/Amenity/Update.cshtml
@model BookingVilla.ViewModels.AmenityVM

<div class="w-100 card border-0 p-4">
	<div class="card-header bg-dark bg-gradient m-lg-0 py-3">
		<div class="row">
			<div class="col-12 text-center">
				<h1 class="text-white-50 py-2">Update Amenity</h1>
			</div>
		</div>
	</div>
	<div class="card-body border p-4">
		<form method="post" class="row">
			<input asp-for="Amenity.Id" hidden />
			<div class="p-3">
				<div asp-validation-summary="ModelOnly" class="text-info"></div>
				<div class="form-floating py-1 col-12">
					<select asp-for="@Model.Amenity.VillaId" asp-items="@Model.VillaList"
							class="form-select border shadow">
						<option disabled selected>- Select Villa - </option>
					</select>
					<label asp-for="Amenity.VillaId" class="ms-2"></label>
					<span asp-validation-for="Amenity.VillaId" class="text-danger"></span>
				</div>
				<div class="form-floating py-1 col-12">
					<input asp-for="Amenity.Name" class="form-control border shadow" />
					<label asp-for="Amenity.Name" class="ms-2"></label>
					<span asp-validation-for="Amenity.Name" class="text-danger"></span>
				</div>
				<div class="form-floating py-1 col-12">
					<input asp-for="Amenity.Description" class="form-control border shadow" />
					<label asp-for="Amenity.Description" class="ms-2"></label>
					<span asp-validation-for="Amenity.Description" class="text-danger"></span>
				</div>
			</div>
			<div class="row pt-2">
				<div class="col-6 col-md-5">
					<button type="submit" class="btn btn-success w-100 justify-content-center d-flex">
						<i class="bi bi-plus-circle-dotted"></i> Update
					</button>
				</div>
				<div class="col-6 col-md-5">
					<a asp-controller="Amenity" asp-action="Index" class="btn btn-secondary w-100 justify-content-center d-flex">
						<i class="bi bi-x-circle"></i> Cancel
					</a>
				</div>
			</div>
		</form>
	</div>
</div>

@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}